### ISSUE TITLE
dos2unix bin/ssc

### ISSUE THREAD

**Issue by sbechet** [justinlettau/sql-source-control#7]
CR LF -> LF

Please do it to help linux user :-)

**Comment by winzig** [comment]
I'm assuming this person is having a similar issue to me. I'm on a Mac and our other dev is on Windows. When I try to check in after `ssc pull`, I often see the file showing up as modified, but the only differences are the line endings.

**Comment by justinlettau** [comment]
Could this be handled with Git Config (https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace)?

I looked into changing the line endings (currently using Node's `EOL` const) to be LF. Seems to work but I'm no cross-platform expert. Do you know if it's safe to write LF for all platforms?

**Comment by winzig** [comment]
@justinlettau I don't think the git config is working for this issue, as both my co-worker and I have it set, and we still run into this issue. 

I think changing it to LF will work. If it's a simple change that we could test locally, we could test it out in our environment to verify it's working (I'm on Mac and my co-worker is on Windows).

**Comment by justinlettau** [comment]
@winzig If you can test it locally, that would help expedite it. If you can't, I hope to be able to soon. I made a branch with the potential fix already (see below). Thanks!

https://github.com/justinlettau/sql-source-control/tree/feat-eol

**Comment by winzig** [comment]
We will test it today and get back to you.

**Comment by winzig** [comment]
@justinlettau Sadly this doesn't seem to have helped, assuming we're both in fact running this branch correctly (it's hard to tell for sure because it's the same version number, 1.9.1). What we did:

- Cloned sql-source-control repo 
- Uninstalled ssc locally, both global and local installations of ssc uninstalled
- Ran `npm install && npm link && npm run build` in the ssc clone directory
- Set the text eol handling in our sql repo's .gitattributes to: `* text eol=lf`
- Checked that change into our git repo
- Wiped out our entire SQL repo directory locally, and re-cloned to start from scratch

We then both did a series of edits of a test stored procedure, and we still are seeing "no changes found" frequently, I'm assuming due to some sort of underlying EOL issues still. We also tried .gitattributes with `* text=auto` and continued to have the same kinds of problems.

The end result for us is it seems our positions are reversed... the windows user now routinely sees "no change" diffs, whereas that is what I used to see. ¯\_💩_/¯

**Comment by justinlettau** [comment]
@winzig Thanks for trying. I thought that would have worked 😕 I'll have to play it it some more.

**Comment by winzig** [comment]
I think I'm still having related whitespace issues on 2.1.1, though it's just me working from macOS now, no second person on Windows. After `ssc pull`, I'll see a bunch of SQL resources showing as "modified" but the diffs are empty. If I try to check them in anyway just to clear things out, Github Desktop responds `Commit failed - exit code 1 received`.

UPDATE: I worked around the issue by going to the command line, and "adding" all those modified files. They then disappeared from the list of modified files. ¯\_💩_/¯
