### ISSUE TITLE
SSC PULL -> deletes generated files

### ISSUE THREAD

**Issue by zote41** [justinlettau/sql-source-control#9]
When I launch this command and I has the output.root set to './' on Windows,  doesn't exclude the files found, and the files already generated will be deleted.

the problem is here
```
glob.sync(config.output.root + "/**/*.sql")
-> ['./test/test.sql']

path.join(config.output.root, 'test','test.sql')
-> 'test\test.sql'
```

**Comment by justinlettau** [comment]
By design, the `pull` command will delete local sql files that are not found in the database. This is to ensure when a database object is deleted (like a table or proc), the associated source control files are deleted as well.

If you are describing something else, could you provide some more details? Thanks.

**Comment by josefstr** [comment]
I'm experiencing the same, running `ssc pull` on windows. The existing files get deleted, the output looks like:
```
Creating 'server.master\schemas\dbo.sql' ...
Creating 'server.master\schemas\dbo.sql' ...
Creating 'server.master\tables\dbo.TableName1.sql' ...
Creating 'server.master\tables\dbo.TableName2.sql' ...
Removing './server.master/schemas/dbo.sql' ...
Removing './server.master/tables/dbo.TableName1.sql' ...
Removing './server.master/tables/dbo.TableName2.sql' ...
```

I'm running `ssc pull` with the default config on a windows git bash.
Is there anything I can provide to fix this problem?
